export { default as Footer } from './Footer'
export { default as Landing } from './Landing'
export { default as About } from './About'
export { default as Contact } from './Contact'
export { default as Header } from './Header'
