import React, { useRef, useEffect, useState } from 'react'
import { useTranslation } from 'react-i18next'
import { Box, Typography, useColorScheme } from '@mui/joy'
import WarningAmberRoundedIcon from '@mui/icons-material/WarningAmberRounded'
import mermaid from 'mermaid'
import DOMPurify from 'dompurify'

export default function MermaidRenderer({ code }) {
  const { t } = useTranslation()
  const { mode } = useColorScheme()
  const ref = useRef(null)
  const [svg, setSvg] = useState('')
  const [error, setError] = useState(null)

  useEffect(() => {
    if (code && ref.current) {
      // Re-initialize with correct theme before each render so light/dark
      // mode changes are reflected in the SVG output.
      //
      // Root cause of invisible text: Mermaid embeds a <style> block in the SVG
      // that defines node label colors. DOMPurify (v3) strips <style> blocks from
      // SVG by default (XSS vector). Without that <style>, text fill falls back to
      // the browser default and becomes invisible against the panel background.
      //
      // Fix: pass explicit themeVariables so Mermaid bakes color values into
      // inline SVG attributes (fill=, stroke=) rather than relying on a <style>
      // block. We also allow the Mermaid <style> through DOMPurify below since
      // it is generated by Mermaid, not from user input.
      const isDark = mode === 'dark'
      mermaid.initialize({
        startOnLoad: false,
        theme: 'base',
        themeVariables: isDark
          ? {
              // Dark mode palette — node boxes, text, edges
              primaryColor: '#1e3a5f',
              primaryTextColor: '#e0eaff',
              primaryBorderColor: '#3b6ea8',
              lineColor: '#7ba3d0',
              secondaryColor: '#162d47',
              tertiaryColor: '#0f1d2e',
              background: '#0b1929',
              mainBkg: '#1e3a5f',
              nodeBorder: '#3b6ea8',
              clusterBkg: '#162d47',
              titleColor: '#e0eaff',
              edgeLabelBackground: '#162d47',
              nodeTextColor: '#e0eaff',
              labelColor: '#e0eaff',
              labelTextColor: '#e0eaff',
              fontFamily: 'Inter, sans-serif'
            }
          : {
              // Light mode palette
              primaryColor: '#dbeafe',
              primaryTextColor: '#1e3a5f',
              primaryBorderColor: '#3b6ea8',
              lineColor: '#3b6ea8',
              secondaryColor: '#eff6ff',
              tertiaryColor: '#f0f7ff',
              background: '#ffffff',
              mainBkg: '#dbeafe',
              nodeBorder: '#3b6ea8',
              clusterBkg: '#eff6ff',
              titleColor: '#1e3a5f',
              edgeLabelBackground: '#eff6ff',
              nodeTextColor: '#1e3a5f',
              labelColor: '#1e3a5f',
              labelTextColor: '#1e3a5f',
              fontFamily: 'Inter, sans-serif'
            },
        securityLevel: 'loose',
        fontFamily: 'Inter, sans-serif',
        // Mermaid v10+ defaults to htmlLabels:true for flowchart/mindmap/ER,
        // rendering node text as <foreignObject> HTML. DOMPurify strips
        // <foreignObject> (XSS vector), leaving boxes with no visible text.
        // Force SVG-native <text> elements so all diagram types render correctly.
        htmlLabels: false
      })
      setSvg('')
      setError(null)
      const id = `mermaid-${Date.now()}`
      mermaid
        .render(id, code)
        .then((result) => {
          // Allow Mermaid's own <style> block through DOMPurify — it is
          // generated internally (not from user input) and contains the color
          // rules for node labels. Without it, SVG text nodes lose their fill.
          const clean = DOMPurify.sanitize(result.svg, {
            ADD_TAGS: ['style'],
            FORCE_BODY: false,
            USE_PROFILES: { svg: true, svgFilters: true }
          })
          setSvg(clean)
          setError(null)
        })
        .catch(() => {
          setError(t('aiMagic.diagram.renderError'))
        })
    }
  }, [code, mode, t])

  if (error) {
    return (
      <Box
        sx={{
          p: 4,
          textAlign: 'center',
          color: 'danger.plainColor',
          bgcolor: 'danger.softBg',
          borderRadius: 'md'
        }}
      >
        <Typography level='title-md' sx={{ mb: 1 }} startDecorator={<WarningAmberRoundedIcon />}>
          {t('aiMagic.diagram.renderError')}
        </Typography>
      </Box>
    )
  }

  return (
    <div
      ref={ref}
      className='mermaid-diagram-host'
      dangerouslySetInnerHTML={{ __html: svg }}
      style={{ width: '100%', overflow: 'auto', textAlign: 'center' }}
    />
  )
}
